[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = ['cd org-manager && pip install -r requirements.txt']

[phases.start]
cmds = ['cd org-manager && uvicorn app.main:app --host 0.0.0.0 --port $PORT']
