"""Add user approval system with roles and permissions

Revision ID: 7ba696f0e91e
Revises: 99dd6b9ca36d
Create Date: 2025-10-16 19:06:24.001237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba696f0e91e'
down_revision: Union[str, None] = '99dd6b9ca36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_orgs_id', table_name='orgs')
    op.drop_table('orgs')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=12), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('orgs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('faccao', sa.VARCHAR(), nullable=False),
    sa.Column('fabricacao', sa.VARCHAR(), nullable=True),
    sa.Column('contato', sa.VARCHAR(), nullable=True),
    sa.Column('membros_ativos', sa.INTEGER(), nullable=True),
    sa.Column('data_entrega', sa.DATE(), nullable=True),
    sa.Column('discord_lider', sa.VARCHAR(), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=6), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('tags_fabricacao', sa.TEXT(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('entregue', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orgs_id', 'orgs', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('target_table', sa.VARCHAR(), nullable=False),
    sa.Column('target_id', sa.INTEGER(), nullable=False),
    sa.Column('details', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_id', 'audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###
